Define Assertj version
datastax/cassandra-quarkus pull request #205
Opened 2022-01-28 11:06 UTC by gsmet

Assertj version is not enforced by the Quarkus BOM anymore.

Due to some repeated binary compatibility issues, we had to remove it from the BOM.

Any chance you could release a new version with this fix before February 1st? We will need it for the 2.7 Quarkus Platform release.

2022-01-28 11:07 UTC, gsmet commented
Ah, wait, no sorry, we don't need a release right now, we will need one for 2.8. But it would be nice to merge it ASAP so that we can have the Ecosystem CI green.

2022-01-28 11:09 UTC, gsmet commented
Still probably a good idea to do a release soon so that we don't forget about it :).

2022-01-28 11:51 UTC, adutra requested changes
Thank you @gsmet we will look into getting a new release out soonish!

I think `runtime/.pom.xml.swp` was committed by mistake, could you please remove it?

2022-01-28 11:53 UTC, gsmet commented
> I think runtime/.pom.xml.swp was committed by mistake, could you please remove it?

Raaah. Will do, sorry about that.

2022-01-28 11:54 UTC, gsmet commented
Done. That's what I get for doing things in batches.

2022-01-28 13:43 UTC, adutra commented
> Done. That's what I get for doing things in batches.

No worries at all, I love when people report issues AND provide the fix at the same time :-)

Just one general remark: wouldn't it be simpler to declare AssertJ only in the parent pom and in the quickstart pom? The parent pom could look like this:

```xml
  <properties>
    <assertj.version>3.22.0</assertj.version>
  </properties>
  <dependencyManagement>
    <dependencies>
      <dependency>
        <groupId>org.assertj</groupId>
        <artifactId>assertj-core</artifactId>
        <version>${assertj.version}</version>
      </dependency>
    </dependencies>
  </dependencyManagement>
```

As far as I can tell, this produces the same effect as declaring AssertJ in all modules that use it..

2022-01-28 13:46 UTC, gsmet commented
No. Because if we do that, it would be part of your BOM and we don't want that. Keep in mind that the BOM inherits any dependency management coming from the parents (we had some very bad surprises in Quarkus with various components bringing a ton of unrelated things with their BOM).

What we do for Quarkus projects is that we have a `build-parent/pom.xml` with this sort of things and the BOM is explicitly not using this one.

2022-01-28 17:03 UTC, adutra approved these changes

2022-02-01 09:48 UTC, gsmet commented
Any chance this could be merged soon? Working on getting our Ecosystem CI green.

2022-02-01 14:51 UTC, merged

2022-02-01 14:52 UTC, adutra commented
Sure thing, sorry for the delay!

2022-02-02 20:52 UTC, adutra commented
> Ah, wait, no sorry, we don't need a release right now, we will need one for 2.8. But it would be nice to merge it ASAP so that we can have the Ecosystem CI green.

@gsmet what's the ETA for Quarkus 2.8? As in, when to you need us to release? :-)

2022-02-02 20:54 UTC, gsmet commented
If you release one month from now, that should be OK.